use std::path::Path;

const TEMPLATE: &str = r#"# vex.toml — generated by vex-mcp init
# VEX_CONFIG=/absolute/path/to/vex.toml  vex-mcp <server-command> [args...]

[server]
id = "{server_id}"

[policy]
default_action = "deny"

allowed_tools = [
  # "read_file",
  # "list_directory",
  # "search_*",             # * ? [...] are glob wildcards
]

# blocked_tools = []        # always blocked, even if in allowed_tools
# confirmation_required = []

[audit]
path = "vex-audit.log"      # verify with: vex-mcp verify

# [rate_limit]
# max_calls_per_minute = 60
# max_message_bytes = 1048576
"#;

pub fn run(args: &[String]) -> anyhow::Result<()> {
    let mut server_id = "my-server".to_owned();
    let mut output = "vex.toml".to_owned();
    let mut force = false;

    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--server" => {
                i += 1;
                server_id = args
                    .get(i)
                    .ok_or_else(|| anyhow::anyhow!("--server requires a value"))?
                    .clone();
            }
            "--output" => {
                i += 1;
                output = args
                    .get(i)
                    .ok_or_else(|| anyhow::anyhow!("--output requires a value"))?
                    .clone();
            }
            "--force" => force = true,
            other => anyhow::bail!("unknown flag `{other}`"),
        }
        i += 1;
    }

    if Path::new(&output).exists() && !force {
        anyhow::bail!("`{output}` already exists (use --force to overwrite)");
    }

    let content = TEMPLATE.replace("{server_id}", &server_id);
    std::fs::write(&output, content)
        .map_err(|e| anyhow::anyhow!("could not write `{output}`: {e}"))?;
    println!("wrote {output}");
    Ok(())
}
